defmodule HybridsocialWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :hybridsocial

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_hybridsocial_key",
    signing_salt: "Qngot0cf",
    same_site: "Lax"
  ]

  socket "/socket", HybridsocialWeb.UserSocket,
    websocket: true,
    longpoll: false

  # socket "/live", Phoenix.LiveView.Socket,
  #   websocket: [connect_info: [session: @session_options]],
  #   longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :hybridsocial,
    gzip: not code_reloading?,
    only: HybridsocialWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Serve uploaded media files from the uploads directory (runtime path)
  plug :serve_uploads

  defp serve_uploads(conn, _opts) do
    uploads_dir = Hybridsocial.Media.Backends.Local.uploads_dir()

    Plug.Static.call(
      conn,
      Plug.Static.init(at: "/uploads", from: uploads_dir, gzip: false)
    )
  end

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :hybridsocial
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, {:multipart, length: 100_000_000}, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    length: 1_000_000

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug HybridsocialWeb.Plugs.SecurityHeaders

  plug :cors_plug

  defp cors_plug(conn, _opts) do
    origins = Application.get_env(:hybridsocial, :cors_origins, [
      "http://localhost:5173",
      "http://localhost:4000"
    ])

    opts = CORSPlug.init(origin: origins, expose: ["link"], credentials: true)
    CORSPlug.call(conn, opts)
  end

  plug HybridsocialWeb.Router
end
